### ISSUE TITLE
Can't open settings (Eyes Guard is already running.)

### ISSUE THREAD

**Issue by Krzeszny** [avestura/EyesGuard#49]
I don't know if I'm dumb or this app isn't working properly. I've installed it from the Microsoft store.
When I click the app's icon, it only says "Eyes Guard is already running. You can't run multiple instances of this software." When I right-click it, it only gives me the option to pin/unpin it.

How do I open settings then?

OS: Windows 10

**Comment by avestura** [comment]
Eyes Guard is already running minimized in the tray. It notifies you about this the first time it launches. (Bad UX probabely)

![image](https://github.com/avestura/EyesGuard/assets/9091958/961370e4-2cd2-4f04-9721-9fbbd8642a86)
