### ISSUE TITLE
Add the Ukrainian language

### ISSUE THREAD

**Issue by masterillaGitHub** [avestura/EyesGuard#50]
if necessary, I can do the translation myself, please provide the language file

**Comment by avestura** [comment]
I'd be very happy if you add the Ukrainian language as I don't know the language myself.

Here is a [guide on how to add a new language](https://github.com/avestura/EyesGuard#how-to-contribute-to-translating-app) to the app.

**Comment by masterillaGitHub** [comment]
I added a commit with the language file.
Thanks for the app, it helps a lot
👍
