### ISSUE TITLE
Hover window randomly showing up and not consistently closing

### ISSUE THREAD

**Issue by Ryuk47** [avestura/EyesGuard#55]
**Description**
The tooltip like window that shows when hovering over the Eyes Guard tray icon (Windows 11 Professional), keeps showing up unanticipated at seemingly random times.

**Bug Domain**
Plase check any of the chackboxes that is related to your request:

- [ ] Crash
- [ ] Wrong output
- [ ] Invalid error
- [x] Annoying behavior

**Steps to Reproduce**
1. Hover over the tray icon
2. Observe the tooltip come up
3. It occasionally doesnt dissapear when no longer hovering
4. This behaviour is especially prevalent when moving the cursor across the tray icon rapidly

**Expected behavior**
The tooltip should consistently dissapear when not hovering over the tray icon.

**Screenshots**
![image](https://github.com/avestura/EyesGuard/assets/69385035/309fd052-a75f-4737-badc-94a583a3491b)

**Device info:**
 - OS: Windows 11 Pro
 - OS Version 22621.2283
 - Build Number 1.3.53

**Additional context**
Sometimes the tooltip appears without hovering over it, and notably appears in the top left of the screen rather than the cursor position or the tray icon.

**Comment by avestura** [comment]
That's weird. I also have Windows 11 but that never happened to me.
![image](https://github.com/avestura/EyesGuard/assets/9091958/b2190568-4bfe-4e90-879d-b31bafc2bb6b)

Do you have any shell customization apps installed by any chance?
Or any shortcut that might trigger focus on tray icons (potentially the first one).
Can you move the EyesGuard's tray icon to some place other than first and see if anything changes?

**Comment by Ryuk47** [comment]
I don't know anything about shell customization, but I went through my tray icons and open processes, closing them one by one to identify a culprit. The behaviour dissapears entirely when ending the Wacom_Tablet.exe task that runs a drawing tablet (it is not currently connected). I'll try updating that or just stoppiung the process alltogether.
